default/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from app.views.LoginModule import LoginView, LogoutView, RegistroCliente, RegistroProfissional, StartSystem, \
    StartTestSystem
from app.views.PanelModule import DashboardView, ContractUpdateView, \
    finalizar_contrato_servico, ServicosList, CreateServico, UpdateServico, DeleteServico, ListComentarios, RevisaoView, \
    ClienteList, EditarPerfilView, RejeiteContratoForm, andamento_contrato_servico, ListCupons, CreateCupom, EditCupom, RemoveCupom, DocumentoContratoProfissional, EditEntrada, DeleteEntrada, \
    CreateEntrada, ListEntradas, ListSaidas, CreateSaida, EditSaida, DeleteSaida, FluxoCaixa, get_month_data, ListInteresse, CreateInteresse, UpdateInteresse, DeleteInteresse, ListPropostas, \
    CreateProposta, DeleteProposta, reject_bid, generate_process, ListProcessos, ViewProcesso, FinalizarProcesso, DocumentoContratoComCliente, ComoFuncionaFQEF
from app.views.StoreModule import IndexView, AreaProfissional, ViewServicoDetail, ProfissionalView, SobreView, \
    ContatoView, add_cart, CarrinhoView, remove_item_cart, MeuPerfil, ListServicesProfissionalView, MeusContratosView, \
    DocumentoContrato, gerar_contrato, aplicar_cupom, AvaliacaoView, RegrasETermos, PoliticaPrivacidade, ComoFunciona, PerguntasFrequentes

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/login/$', auth_views.login),

    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', ViewServicoDetail.as_view(), name='view-servico'),
    url(r'^profissionais/$', ProfissionalView.as_view(), name='list-profissionais'),
    url(r'^profissionais/(?P<pk>[0-9]+)/$', ListServicesProfissionalView.as_view(), name='list-services-profissional'),
    url(r'^sobre/$', SobreView.as_view(), name='sobre'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^account/logout/$', LogoutView.as_view(), name='logout'),
    url(r'^registro/$', RegistroCliente.as_view(), name='registro-cliente'),
    url(r'^area-profissional/$', AreaProfissional.as_view(), name='area-profissional'),
    url(r'^area-profissional/registro/$', RegistroProfissional.as_view(), name='registro-profissional'),
    url(r'^contato/$', ContatoView.as_view(), name='fale-conosco'),
    url(r'^add-cart/$', add_cart, name='add-carrinho'),
    url(r'^remove-item-cart/$', remove_item_cart, name='remove-item-carrinho'),
    url(r'^carrinho/(?P<pk>[0-9]+)/$', CarrinhoView.as_view(), name='carrinho'),
    url(r'^meuperfil/(?P<pk>[0-9]+)/$', MeuPerfil.as_view(), name='meu-perfil'),
    url(r'^meuscontratos/$', MeusContratosView.as_view(), name='meus-contratos'),
    url(r'^meuscontratos/documento/(?P<pk>[0-9]+)$', DocumentoContrato.as_view(), name='documento-contrato'),
    url(r'^gerarcontrato/$', gerar_contrato, name='gerar-contrato'),
    url(r'^aplicar-cupom/$', aplicar_cupom, name='aplicar-cupom'),
    url(r'^avaliar/(?P<pk>[0-9]+)/$', AvaliacaoView.as_view(), name='avaliar-servico'),
    url(r'^regras-e-termos/$', RegrasETermos.as_view(), name='regras-e-termos'),
    url(r'^politica-de-privacidade/$', PoliticaPrivacidade.as_view(), name='politica-de-privacidade'),
    url(r'^como-funciona/$', ComoFunciona.as_view(), name='como-funciona'),
    url(r'^perguntas-frequentes/$', PerguntasFrequentes.as_view(), name='perguntas-frequentes'),

    url(r'^startsystemdefault/$', StartSystem.as_view(), name='startsystem'),
    url(r'^starttestdefault/$', StartTestSystem.as_view(), name='starttestsystem'),

    url(r'^painel/$', DashboardView.as_view(), name='dashboard-profissional'),
    url(r'^painel/documento/(?P<pk>[0-9]+)$', DocumentoContratoComCliente.as_view(), name='documento-contrato-com-cliente'),
    url(r'^painel/edit/(?P<pk>[0-9]+)/$', ContractUpdateView.as_view(), name='editar-contrato'),
    url(r'^painel/finalizar/(?P<pk>[0-9]+)/$', finalizar_contrato_servico, name='finalizar-contrato'),
    url(r'^painel/andamento/(?P<pk>[0-9]+)/$', andamento_contrato_servico, name='andamento-contrato'),
    url(r'^painel/rejeite/(?P<pk>[0-9]+)/$', RejeiteContratoForm.as_view(), name='rejeite-contrato-form'),
    url(r'^painel/clientes/$', ClienteList.as_view(), name='list-clientes'),
    url(r'^painel/servicos/$', ServicosList.as_view(), name='list-servicos'),
    url(r'^painel/servicos/create/$', CreateServico.as_view(), name='create-servico'),
    url(r'^painel/servicos/(?P<pk>[0-9]+)/$', UpdateServico.as_view(), name='edit-servico'),
    url(r'^painel/servicos/delete/(?P<pk>[0-9]+)/$', DeleteServico.as_view(), name='delete-servico'),
    url(r'^painel/comentarios/$', ListComentarios.as_view(), name='list-comentarios'),
    url(r'^painel/comentarios/revisao/(?P<pk>[0-9]+)/$', RevisaoView.as_view(), name='revisao-servico'),
    url(r'^painel/perfil/(?P<pk>[0-9]+)/$', EditarPerfilView.as_view(), name='editar-perfil'),
    url(r'^painel/cupons/$', ListCupons.as_view(), name='list-cupons'),
    url(r'^painel/cupons/create/$', CreateCupom.as_view(), name='create-cupom'),
    url(r'^painel/cupons/(?P<pk>[0-9]+)/$', EditCupom.as_view(), name='edit-cupom'),
    url(r'^painel/cupons/delete/(?P<pk>[0-9]+)/$', RemoveCupom.as_view(), name='delete-cupom'),
    url(r'^painel/entradas/$', ListEntradas.as_view(), name='list-entradas'),
    url(r'^painel/entradas/create/$', CreateEntrada.as_view(), name='create-entrada'),
    url(r'^painel/entradas/(?P<pk>[0-9]+)/$', EditEntrada.as_view(), name='edit-entrada'),
    url(r'^painel/entradas/delete/(?P<pk>[0-9]+)/$', DeleteEntrada.as_view(), name='delete-entrada'),
    url(r'^painel/saidas/$', ListSaidas.as_view(), name='list-saidas'),
    url(r'^painel/saidas/create/$', CreateSaida.as_view(), name='create-saida'),
    url(r'^painel/saidas/(?P<pk>[0-9]+)/$', EditSaida.as_view(), name='edit-saida'),
    url(r'^painel/saidas/delete/(?P<pk>[0-9]+)/$', DeleteSaida.as_view(), name='delete-saida'),
    url(r'^painel/fluxocaixa/$', FluxoCaixa.as_view(), name='fluxo-caixa'),
    url(r'^painel/fluxocaixa/get-data/$', get_month_data, name='get-data-fluxo'),
    url(r'^painel/faz-que-eu-faco/$', ComoFuncionaFQEF.as_view(), name='como-funciona-fqef'),
    url(r'^painel/interesses/$', ListInteresse.as_view(), name='list-interesses'),
    url(r'^painel/interesses/create/$', CreateInteresse.as_view(), name='create-interesse'),
    url(r'^painel/interesses/(?P<pk>[0-9]+)/$', UpdateInteresse.as_view(), name='edit-interesse'),
    url(r'^painel/interesses/delete/(?P<pk>[0-9]+)/$', DeleteInteresse.as_view(), name='delete-interesse'),
    url(r'^painel/propostas/$', ListPropostas.as_view(), name='list-propostas'),
    url(r'^painel/propostas/create/(?P<pk>[0-9]+)/$', CreateProposta.as_view(), name='create-proposta'),
    url(r'^painel/propostas/delete/(?P<pk>[0-9]+)/$', DeleteProposta.as_view(), name='delete-proposta'),
    url(r'^painel/propostas/reject/(?P<pk>[0-9]+)/$', reject_bid, name='rejeitar-proposta'),
    url(r'^painel/propostas/acept/(?P<pk>[0-9]+)/$', generate_process, name='aceitar-proposta'),
    url(r'^painel/processo/documento/(?P<pk>[0-9]+)$', DocumentoContratoProfissional.as_view(), name='documento-contrato-pro'),
    url(r'^painel/processos/$', ListProcessos.as_view(), name='list-processos'),
    url(r'^painel/processos/view/(?P<pk>[0-9]+)/$', ViewProcesso.as_view(), name='view-processo'),
    url(r'^painel/processos/finalizar/(?P<pk>[0-9]+)/$', FinalizarProcesso.as_view(), name='finalizar-processo'),
]

app/models.py
# coding=utf-8
from __future__ import unicode_literals

from base64 import b64encode

import pyimgur
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from djmoney.models.fields import MoneyField
from djmoney.money import Money

from app.views.TelegramAPI import send_mail_and_telegram_admin


class TimeStamped(models.Model):
    class Meta:
        abstract = True

    created_at = models.DateTimeField(auto_now_add=True)
    published_at = models.DateTimeField(auto_now=True)


class BaseAddress(models.Model):
    class Meta:
        abstract = True

    cep = models.CharField(max_length=200, blank=True, null=True, verbose_name='CEP')
    bairro = models.CharField(max_length=200, blank=True, null=True, verbose_name='Bairro')
    endereco = models.CharField(max_length=300, blank=True, null=True, verbose_name='Endereço')
    numero = models.CharField(max_length=5, blank=True, null=True, verbose_name='Número')
    cidade = models.CharField(max_length=200, blank=True, null=True, verbose_name='Cidade')
    estado = models.CharField(max_length=200, blank=True, null=True, verbose_name='Estado')
    complemento = models.CharField(max_length=300, blank=True, null=True, verbose_name='Ponto de Referência')
    lat = models.CharField(max_length=300, blank=True, null=True)
    lng = models.CharField(max_length=300, blank=True, null=True)

    def save(self, *args, **kwargs):
        try:
            self.numero = self.numero.replace("_", "")
        except (Exception,):
            pass
        super(BaseAddress, self).save(*args, **kwargs)


class CommonUserData(TimeStamped, BaseAddress):
    class Meta:
        abstract = True

    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True, blank=True, null=True)
    telefone_1 = models.CharField(max_length=30, blank=True, null=True)
    whatsapp = models.CharField(max_length=30, blank=True, null=True)
    photo = models.URLField(blank=True, null=True, default='https://placehold.it/300x300')
    cpf = models.CharField(max_length=100, blank=True, null=True, default="")
    cnpj = models.CharField(max_length=100, blank=True, null=True, default="")
    is_online = models.BooleanField(default=False)
    file = models.FileField(blank=True, null=True)
    email = models.EmailField(blank=True, null=True)

    def save(self, *args, **kwargs):
        try:
            self.telefone_1 = self.telefone_1.replace("_", "")
            self.whatsapp = self.whatsapp.replace("_", "")
        except (Exception,):
            pass
        try:
            CLIENT_ID = "cdadf801dc167ab"
            bencode = b64encode(self.file.read())
            client = pyimgur.Imgur(CLIENT_ID)
            r = client._send_request('https://api.imgur.com/3/image', method='POST', params={'image': bencode})
            file = r['link']
            self.photo = file
        except (Exception,):
            pass
        super(CommonUserData, self).save(*args, **kwargs)

    def __str__(self):
        return u'%s %s' % (self.user.first_name, self.user.last_name)

    def __unicode__(self):
        return u'%s %s' % (self.user.first_name, self.user.last_name)


class TelegramBot(TimeStamped):
    class Meta:
        verbose_name = u'Telegram Bot'
        verbose_name_plural = u'Telegram Bots'

    first_name = models.CharField(max_length=300, blank=True, null=True)
    chat_id = models.CharField(max_length=300, blank=True, null=True)
    last_name = models.CharField(max_length=300, blank=True, null=True)
    username = models.CharField(max_length=300, blank=True, null=True)
    is_approved = models.BooleanField(default=True)

    def __unicode__(self):
        return u'%s' % self.chat_id

    def __str__(self):
        return u'%s' % self.chat_id


class EmailOuTelegramaAdmin(TimeStamped):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    message = models.TextField()
    title = models.CharField(max_length=200)
    enviado = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        customuser = None
        try:
            customuser = self.user.cliente
        except (Exception,):
            print('Nao eh cliente')
        try:
            customuser = self.user.profissional
        except (Exception,):
            print('Nao eh profissional')
        try:
            send_mail_and_telegram_admin(customuser, self.message, self.title)
            self.enviado = True
        except (Exception,):
            print('erro ao enviar mensagem')
        return super(EmailOuTelegramaAdmin, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'%s' % self.id

    def __str__(self):
        return u'%s' % self.id


class RecycleTelegramItem(TimeStamped):
    class Meta:
        verbose_name = u'Telegram Bot Reciclavel'
        verbose_name_plural = u'Bots Reciclaveis'

    first_name = models.CharField(max_length=300, blank=True, null=True)
    chat_id = models.CharField(max_length=300, blank=True, null=True)
    last_name = models.CharField(max_length=300, blank=True, null=True)
    username = models.CharField(max_length=300, blank=True, null=True)

    def __unicode__(self):
        return u'%s' % self.id

    def __str__(self):
        return u'%s' % self.id


class Cliente(CommonUserData):
    class Meta:
        verbose_name = u'Cliente'
        verbose_name_plural = u'Clientes'


class CategoriaDeProfissional(TimeStamped):
    class Meta:
        verbose_name = u'Categoria de Profissional'
        verbose_name_plural = u'Categorias de Profissional'

    categoria = models.CharField(max_length=300, blank=True, null=True)
    descricao = models.TextField(blank=True, null=True)

    def __str__(self):
        return "%s" % self.categoria

    def __unicode__(self):
        return "%s" % self.categoria


class Profissional(CommonUserData):
    class Meta:
        verbose_name = u'Profissional'
        verbose_name_plural = u'Profissionais'

    categoria = models.ForeignKey(CategoriaDeProfissional, blank=True, null=True, on_delete=models.CASCADE)
    telefone_2 = models.CharField(max_length=30, blank=True, null=True)
    link_facebook = models.URLField(blank=True, null=True)
    link_instagram = models.URLField(blank=True, null=True)
    url_site = models.URLField(blank=True, null=True)
    is_approved = models.BooleanField(default=False)
    telegram_bot = models.ForeignKey(TelegramBot, blank=True, null=True)
    receber_pelo_sistema = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        try:
            self.telefone_2 = self.telefone_2.replace("_", "")
        except (Exception,):
            pass
        super(Profissional, self).save(*args, **kwargs)


class CategoriaDeServico(TimeStamped):
    class Meta:
        verbose_name = u'Categoria de Servico'
        verbose_name_plural = u'Categorias de Servico'

    categoria = models.CharField(max_length=300, blank=True, null=True, )
    profissional = models.ForeignKey(Profissional, blank=True, null=True, on_delete=models.CASCADE)
    disponivel = models.BooleanField(default=True)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return "%s" % self.categoria

    def __unicode__(self):
        return "%s" % self.categoria


class Servico(TimeStamped):
    class Meta:
        verbose_name = u'Servico'
        verbose_name_plural = u'Servicos'

    categoria = models.ForeignKey(CategoriaDeServico, blank=True, null=True)
    titulo = models.CharField(max_length=300, blank=True, null=True)
    descricao = models.TextField(blank=True, null=True)
    profissional = models.ForeignKey(Profissional, blank=True, null=True)
    disponivel = models.BooleanField(default=True)
    is_approved = models.BooleanField(default=True)
    valor_a_combinar = models.BooleanField(default=False)
    valor_base = MoneyField(max_digits=14, decimal_places=2, validators=[MinValueValidator(Money(0, 'BRL'))])

    def __str__(self):
        return "%s" % self.titulo

    def __unicode__(self):
        return "%s" % self.titulo

    def save(self, *args, **kwargs):
        super(Servico, self).save(*args, **kwargs)


class AdicionalDeServico(TimeStamped):
    class Meta:
        verbose_name = u'Adicional de Servico'
        verbose_name_plural = u'Adicionais de Servicos'

    titulo = models.CharField(max_length=100, blank=True, null=True)
    descricao = models.CharField(max_length=300, blank=True, null=True)
    servico = models.ForeignKey(Servico, blank=True, null=True, on_delete=models.CASCADE)
    valor = MoneyField(max_digits=14, decimal_places=2, validators=[MinValueValidator(Money(0, 'BRL'))])
    disponivel = models.BooleanField(default=True)
    is_approved = models.BooleanField(default=True)

    def __unicode__(self):
        return u'%s' % self.titulo

    def __str__(self):
        return u'%s' % self.titulo

    def save(self, *args, **kwargs):
        self.valor = float(str(self.valor).replace(',', '.'))
        super(AdicionalDeServico, self).save(*args, **kwargs)


class FotoServico(TimeStamped):
    class Meta:
        verbose_name = u'Foto de Servico'
        verbose_name_plural = u'Fotos de Servicos'

    servico = models.ForeignKey(Servico, blank=True, null=True, on_delete=models.CASCADE)
    url = models.URLField(blank=True, null=True, default='https://placehold.it/300x300')
    file = models.FileField(blank=True, null=True)
    is_approved = models.BooleanField(default=True)

    def __unicode__(self):
        return u'%s' % self.url

    def __str__(self):
        return u'%s' % self.url

    def save(self, *args, **kwargs):
        try:
            CLIENT_ID = "cdadf801dc167ab"
            bencode = b64encode(self.file.read())
            client = pyimgur.Imgur(CLIENT_ID)
            r = client._send_request('https://api.imgur.com/3/image', method='POST', params={'image': bencode})
            file = r['link']

app/templates/panel/update-cupom.html
{% extends 'panel/base.html' %}
{% load staticfiles %}
{% load filters %}

{% block content %}
        {% include 'utils/breadcrumb.html' with title='Atualizar Cupom' subtitle='Atualize os atributos do cupom criado.' link1='Cupons' link2='Atualizar Cupom' %}

    <div class="box box-primary" style="margin-top: 30px;">
        <div class="box-header">
            <h3 class="box-title">
                <center style="font-size: 20px;">Atualizar Cupom</center>
            </h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                        {{ form.as_p }}
                    </div>
                </div>
                <hr/>
            </div>
            <!-- /.box-body -->
            <div class=" box-footer ">
                <a href="{% url 'list-cupons' %}" id="btn_cancelar"
                   class="btn btn-default pull-left">Voltar</a>
                <button type="submit" id="btn_salvar" class="btn btn-primary pull-right">Editar
                </button>
            </div>
        </form>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sistema').addClass('active');
            $('#cupons').addClass('active');
            $('[name=valor_de_desconto_1]').addClass('hidden');

            tour = new Tour({
                name: 'update_cupom',
                backdrop: true,
                template: "<div class='popover tour'><div class='arrow'></div><h3 class='popover-title'></h3><div class='popover-content'></div><div class='popover-navigation'><button class='btn btn-default' data-role='prev'>« Anterior</button><span data-role='separator'>|</span><button id='prox' class='btn btn-default' data-role='next'>Próximo »</button><button id='fim' class='btn btn-default hidden' data-role='end'>Finalizar</button> </div></div>",
                steps: [
                    {
                        element: ".box.box-primary",
                        placement: "top",
                        title: "Editar Cupom",
                        content: "Aqui temos o formulário para editar um cupom."
                    },
                    {
                        element: "#id_codigo",
                        placement: "top",
                        title: "Codigo",
                        content: "Insira aqui o novo codigo do cupom, se necessário. Exemplo: #VALE10"
                    },
                    {
                        element: "#id_valor_de_desconto_0",
                        placement: "top",
                        title: "Valor de desconto",
                        content: "Insira aqui o valor de desconto do cupom. Exemplo: 10.00"
                    },
                    {
                        element: "#id_is_approved",
                        placement: "top",
                        title: "Disponibilidade",
                        content: "Se este cupom não estiver mais ativo, desmarque esta caixa. Se não, deixe marcado. "
                    },
                    {
                        element: "#btn_salvar",
                        title: "Editar",
                        placement: "left",
                        content: "Utilize este botão para atualizar o cupom.",
                        onShow: function (tour) {
                            var timeOut = setTimeout(function () {
                                $('#fim').removeClass('hidden');
                                $('#prox').addClass('hidden');
                                timeOut = setTimeout(function () {
                                    $('#fim').removeClass('hidden');
                                    clearTimeout(timeOut);
                                }, 500);
                            }, 500);

                        }
                    }

                ]
            });
        });
    </script>

{% endblock %}

app/templates/panel/update-servico.html
{% extends 'panel/base.html' %}
{% load staticfiles %}
{% load filters %}

{% block content %}
    {% include 'utils/breadcrumb.html' with title='Atualizar Serviço' subtitle='Altere os atributos do seu serviço.' link1='Serviços' link2='Atualizar Serviço' %}
    <div class="box box-primary" style="margin-top: 30px;">
        <div class="box-header">
            <h3 class="box-title">
                <center style="font-size: 20px;">Atualizar Serviço</center>
            </h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                        {{ form.as_p }}
                    </div>
                </div>
                <hr/>
                <h3>Fotos</h3>
                <div class="row" id="space_fotos">
                    <div class="col-md-12">
                        {{ fotoservicoset.management_form }}
                        <table class="table">
                            {% for form in fotoservicoset.forms %}
                                {% if forloop.first %}
                                    <thead>
                                    <tr>
                                        {% for field in form.visible_fields %}
                                            <th>{{ field.label|capfirst }}</th>
                                        {% endfor %}
                                    </tr>
                                    </thead>
                                {% endif %}
                                <tr class="fotoservicoset_row">
                                    {% for field in form.visible_fields %}
                                        <td>
                                            {# Include the hidden fields in the form #}
                                            {% if forloop.first %}
                                                {% for hidden in form.hidden_fields %}
                                                    {{ hidden }}
                                                {% endfor %}
                                            {% endif %}
                                            {{ field.errors.as_ul }}
                                            {% if field.field.widget.attrs.class == 'hidden' %}
                                                {% if field.value %}
                                                    <img src="{{ field.value }}" class="img-responsive"
                                                         style="width: 60px;"/>
                                                {% endif %}
                                            {% else %}
                                                {{ field }}
                                            {% endif %}
                                        </td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </table>
                        <script src="{% static 'theme-store/js/jquery.formset.js' %}"></script>
                        <script type="text/javascript">
                            $('.fotoservicoset_row').formset({
                                addText: 'Inserir Fotos',
                                deleteText: 'Remover',
                                prefix: 'fotoservico_set'
                            });
                        </script>
                    </div>
                </div>
                <hr/>
            </div>
            <!-- /.box-body -->
            <div class=" box-footer ">
                <a href="{% url 'list-servicos' %}" id="btn_cancelar"
                   class="btn btn-default pull-left">Voltar</a>
                <button type="submit" id="btn_salvar" class="btn btn-primary pull-right">Editar
                </button>
            </div>
        </form>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('[name=valor_base_1]').addClass('hidden');
            if ($('[name=valor_a_combinar]').is(':checked')) {
                if ($('[name=valor_a_combinar]').prop("checked") == true) {
                    $('[name=valor_base_0]').hide();
                    $('[name=valor_base_0]').val('0.0');
                    $('[name=valor_base_0]').attr('required', false);
                } else if ($('[name=valor_a_combinar]').prop("checked") == false) {
                    $('[name=valor_base_0]').show();
                }
            }

            $('[name=valor_a_combinar]').click(function () {
                if ($(this).prop("checked") == true) {
                    $('[name=valor_base_0]').hide();
                } else if ($(this).prop("checked") == false) {
                    $('[name=valor_base_0]').show();
                }
            });

            $('input[type=checkbox]').removeClass('form-control');
            $('.add-row').click(function (evt) {
                $('input[type=checkbox]').removeClass('form-control');
            });

            $('#sistema').addClass('active');
            $('#servicos').addClass('active');

            tour = new Tour({
                name: 'update_servico',
                backdrop: true,
                template: "<div class='popover tour'><div class='arrow'></div><h3 class='popover-title'></h3><div class='popover-content'></div><div class='popover-navigation'><button class='btn btn-default' data-role='prev'>« Anterior</button><span data-role='separator'>|</span><button id='prox' class='btn btn-default' data-role='next'>Próximo »</button><button id='fim' class='btn btn-default hidden' data-role='end'>Finalizar</button> </div></div>",
                steps: [
                    {
                        element: ".box.box-primary",
                        placement: "top",
                        title: "Editar Serviço",
                        content: "Aqui temos o formulário para editar um serviço."
                    },
                    {
                        element: ".box.box-primary",
                        placement: "top",
                        title: "Editar um serviço",
                        content: "Através dos campos vamos definir os novos atributos que serão editados."
                    },
                    {
                        element: "#id_titulo",
                        placement: "top",
                        title: "Título",
                        content: "Insira aqui o novo titulo do Serviço, se necessário."
                    },
                    {
                        element: "#id_descricao",
                        placement: "top",
                        title: "Descrição",
                        content: "Insira aqui a descrição do Serviço, se necessário."
                    },
                    {
                        element: "#id_valor_base_0",
                        placement: "top",
                        title: "Preço",
                        content: "Insira aqui o novo preço do Serviço, se necessário."
                    },
                    {
                        element: "#id_disponivel",
                        placement: "top",
                        title: "Disponibilidade",
                        content: "Se este cupom não estiver mais ativo, desmarque esta caixa. Se não, deixe marcado. "
                    },
                    {
                        element: "#space_fotos",
                        placement: "top",
                        title: "Fotos",
                        content: "Use este espaço para adicionar as fotos dos seu serviço  a ser oferecido. "
                    },
                    {
                        element: "#id_fotoservico_set-0-file",
                        placement: "top",
                        title: "Campo de Foto",
                        content: "Clique neste espaço e indique qual foto você deseja fazer upload."
                    },
                    {
                        element: ".add-row",
                        placement: "top",
                        title: "Adicionar mais Fotos",
                        content: "Clique neste botão caso desejar adicionar mais fotos."
                    },
                    {
                        element: ".delete-row",
                        placement: "top",
                        title: "Remover Fotos",
                        content: "Clique neste botão caso desejar remover alguma foto."
                    },
                    {
                        element: "#btn_salvar",
                        title: "Atualizar",
                        placement: "left",
                        content: "Utilize este botão para salvar as alterações no serviço.",
                        onShow: function (tour) {
                            var timeOut = setTimeout(function () {
                                $('#fim').removeClass('hidden');
                                $('#prox').addClass('hidden');
                                timeOut = setTimeout(function () {
                                    $('#fim').removeClass('hidden');
                                    clearTimeout(timeOut);
                                }, 500);
                            }, 500);

                        }
                    }

                ]
            });
        });
    </script>
    <script>
        $('.add-row').addClass('btn btn-primary');
    </script>

{% endblock %}